export const businessConstants = {
  BUSINESS_LIST_REQUEST: 'BUSINESS_LIST_REQUEST',
  BUSINESS_LIST_SUCCESS: 'BUSINESS_LIST_SUCCESS',
  BUSINESS_LIST_FAILURE: 'BUSINESS_LIST_FAILURE',

  BUSINESS_LIST_CLEAN_ERROR: 'BUSINESS_LIST_CLEAN_ERROR',

  BUSINESS_DETAILS_REQUEST: 'BUSINESS_DETAILS_REQUEST',
  BUSINESS_DETAILS_SUCCESS: 'BUSINESS_DETAILS_SUCCESS',
  BUSINESS_DETAILS_FAILURE: 'BUSINESS_DETAILS_FAILURE',

  ADD_BUSINESS_VIEWED: 'ADD_BUSINESS_VIEWED',
  UPDATE_BUSINESS_LIST: 'UPDATE_BUSINESS_LIST',
};
