export const businessConstants = {
  BUSINESS_LIST_REQUEST: 'BUSINESS_LIST_REQUEST',
  BUSINESS_LIST_SUCCESS: 'BUSINESS_LIST_SUCCESS',
  BUSINESS_LIST_FAILURE: 'BUSINESS_LIST_FAILURE',

  SET_BUSINESS_SELECTED: 'SET_BUSINESS_SELECTED',
  BUSINESS_LIST_CLEAN_ERROR: 'BUSINESS_LIST_CLEAN_ERROR',
};
